# Octave Tutorial: Computing on Data

## 2020년 07월 26일 안상호


### Octave의 장점

- 빠른 프로토타입(알고리즘) 구현 가능 
- 높은 생산성...
- (사족) 통계 : R = 수학 : Octave

In [1]:
A = [1 2; 3 4; 5 6]
B = [11 12; 13 14; 15 16]
C = [1 1; 2 2]

A =

   1   2
   3   4
   5   6

B =

   11   12
   13   14
   15   16

C =

   1   1
   2   2



- 행렬 곱 (`*`)

In [2]:
A * C

ans =

    5    5
   11   11
   17   17



- element-wise 곱 `.*`

일반적으로 **Octave**에서 `.`은 element 단위의 연산을 가능하게 한다.

In [3]:
A .* B

ans =

   11   24
   39   56
   75   96



In [4]:
A .^ 2

ans =

    1    4
    9   16
   25   36



In [8]:
1 ./ A

ans =

   1.00000   0.50000
   0.33333   0.25000
   0.20000   0.16667



In [7]:
v = [1; 2; 3]
1 ./ v % 역수 벡터 

v =

   1
   2
   3

ans =

   1.00000
   0.50000
   0.33333



In [9]:
log(v)
exp(v)

ans =

   0.00000
   0.69315
   1.09861

ans =

    2.7183
    7.3891
   20.0855



In [10]:
abs([-1; 2; 3])

ans =

   1
   2
   3



In [11]:
-v % -1*v

ans =

  -1
  -2
  -3



In [12]:
v + ones(length(v), 1)

ans =

   2
   3
   4



In [13]:
v + 1

ans =

   2
   3
   4



$A^T$: A 전치 행렬

In [14]:
A' 

ans =

   1   3   5
   2   4   6



In [15]:
(A')'

ans =

   1   2
   3   4
   5   6



In [16]:
a = [1 15 2 0.5]
val = max(a)

a =

    1.00000   15.00000    2.00000    0.50000

val =  15


In [17]:
[val, ind] = max(a)

val =  15
ind =  2


In [19]:
a < 3
find(a < 3)

ans =

  1  0  1  1

ans =

   1   3   4



- 마방진(magic squares)

In [29]:
M = magic(3)

M =

   8   1   6
   3   5   7
   4   9   2



In [30]:
[r, c] = find(M >= 7)

r =

   1
   3
   2

c =

   1
   2
   3



## 모든 원소의 합과 곱

In [31]:
sum(a)
prod(a)

ans =  18.500
ans =  15


## 버림, 올림

In [32]:
floor(a)
ceil(a)

ans =

    1   15    2    0

ans =

    1   15    2    1



## 난수 생성과 max 응용

In [33]:
rand(3)

ans =

   0.49106   0.78537   0.17844
   0.73048   0.65239   0.55353
   0.87614   0.61853   0.71780



In [34]:
max(rand(3), rand(3))

ans =

   0.76073   0.83367   0.55076
   0.76318   0.49318   0.71520
   0.68592   0.75489   0.24990



In [35]:
max(M, [], 1) % column별 최댓값, 1

ans =

   8   9   7



In [38]:
max(M) % default는 column별

ans =

   8   9   7



In [37]:
max(M, [], 2) % row별 최댓값, 2
max(M, 5)

ans =

   8
   7
   9

ans =

   8   5   6
   5   5   7
   5   9   5



In [41]:
max(max(M)) == max(M(:))% 모든 원소중 최댓값을 구하는 두가지 방법

ans = 1


In [42]:
M9 = magic(9)

sum(M9, 1) % column별 합계
sum(M9, 2) % row별 합계

M9 =

   47   58   69   80    1   12   23   34   45
   57   68   79    9   11   22   33   44   46
   67   78    8   10   21   32   43   54   56
   77    7   18   20   31   42   53   55   66
    6   17   19   30   41   52   63   65   76
   16   27   29   40   51   62   64   75    5
   26   28   39   50   61   72   74    4   15
   36   38   49   60   71   73    3   14   25
   37   48   59   70   81    2   13   24   35

ans =

   369   369   369   369   369   369   369   369   369

ans =

   369
   369
   369
   369
   369
   369
   369
   369
   369



In [49]:
sum((M9 .* eye(9))(:)) % 대각합 trace(M9)

ans =  369


In [53]:
M9 .* flipud(eye(9)) % 반대쪽 대각선

ans =

    0    0    0    0    0    0    0    0   45
    0    0    0    0    0    0    0   44    0
    0    0    0    0    0    0   43    0    0
    0    0    0    0    0   42    0    0    0
    0    0    0    0   41    0    0    0    0
    0    0    0   40    0    0    0    0    0
    0    0   39    0    0    0    0    0    0
    0   38    0    0    0    0    0    0    0
   37    0    0    0    0    0    0    0    0



# 역행렬

In [55]:
A = magic(3)

temp = pinv(A)

A * temp

A =

   8   1   6
   3   5   7
   4   9   2

temp =

   0.147222  -0.144444   0.063889
  -0.061111   0.022222   0.105556
  -0.019444   0.188889  -0.102778

ans =

   1.0000e+00  -1.2323e-14   6.6613e-15
  -6.9389e-17   1.0000e+00   2.2204e-16
  -5.8911e-15   1.2434e-14   1.0000e+00

